# Local development with Docker Compose.
#
# To start the web app in detached mode:
#   docker-compose up -d
#
# To migrate the database:
#   docker-compose run web python /opt/web/manage.py migrate
#
# To create a superuser:
#   docker-compose run web python /opt/web/manage.py createsuperuser
#
# To stop services:
#   docker-compose down

version: '3'

services:
  db:
    image: postgres:10.11
    ports:
      - "5432:5432"
    volumes: 
      - .postgres-data:/var/lib/postgresql/data
  web:
    build: ./web
    image: reading-quantified-server:latest
    ports:
      - "8000:8000"
    env_file: ./web/.env
    depends_on:
      - db
    volumes: 
      - ./web:/opt/web
    command: python /opt/web/manage.py runserver 0.0.0.0:8000