# Generated by Django 2.1.4 on 2018-12-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181210_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='trello_id',
            field=models.CharField(default='', max_length=36, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='trello_id',
            field=models.CharField(default='', max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
