# Generated by Django 3.0.1 on 2019-12-24 17:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_attachment',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Trello card attachment info. See https://developers.trello.com/reference#cardsidattachments.'),
        ),
    ]
